### ISSUE TITLE
For my setup the slashes are opposite direction on generation

### ISSUE THREAD

**Issue by ArkV1** [L3odr0id/asset_fill#2]
Windows 11 
Flutter 3.7.12 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d9e56e694 (3 weeks ago) • 2023-04-17 21:47:46 -0400
Engine • revision 1a65d409c7
Tools • Dart 2.19.6 • DevTools 2.20.1

**Comment by L3odr0id** [comment]
=)

**Comment by L3odr0id** [comment]
Would you like to fix bugs for windows? I'd be glad to see your contribution

**Comment by ArkV1** [comment]
I can try

**Comment by L3odr0id** [comment]
Uploaded 1.0.2 https://pub.dev/packages/asset_fill
