### ISSUE TITLE
Parent subfolder misssing

### ISSUE THREAD

**Issue by xunreal75** [L3odr0id/asset_fill#5]
if you have an structure like 
 - assets/images/instruction/file1.png
 - assets/images/file2.png

following happens
you create only  - assets/images/instruction/
the parent folder  - assets/images/ is missing in assets catalog

**Comment by L3odr0id** [comment]
There is a really important issue! Thanks a lot! Fixed in https://github.com/L3odr0id/asset_fill/commit/6032321d94b834411339e892ac10df0933cbd782
